server:
  port: 8080
  servlet:
    context-path: /dream-app


spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    name: test
    url: jdbc:mysql://192.168.31.8:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.31.8
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml

logging:
  level:
    com.example.demo.dao : debug

